"""
Auto-generated synthetic data script.
Generated by: AI-Driven Synthetic Data Generator (Stage B)
"""

from faker import Faker
import random

# Initialize Faker with deterministic seed
fake = Faker()
Faker.seed(0)
random.seed(0)

# Data store: table_name -> list of records
data_store = {}

# Initialize table: users
data_store['users'] = []

# Initialize table: posts
data_store['posts'] = []

# Initialize table: comments
data_store['comments'] = []

# Generate rows for: users
for _row_idx_users in range(50):
    _record = {}
    # Primary key (sequential integer)
    _record['id'] = _row_idx_users + 1
    # Faker: user_name
    _record['username'] = fake.user_name()
    # Faker: lexify
    _record['password'] = fake.lexify()
    # Faker: email
    _record['email'] = fake.email()
    data_store['users'].append(_record)

# Generate rows for: posts
for _row_idx_posts in range(50):
    _record = {}
    # Primary key (sequential integer)
    _record['id'] = _row_idx_posts + 1
    # Foreign key -> users.id
    _parent_ids = [r['id'] for r in data_store['users']]
    _record['user_id'] = random.choice(_parent_ids)
    # Faker: sentence
    _record['title'] = fake.sentence()
    # Faker: paragraph
    _record['content'] = fake.paragraph()
    # Faker: date_this_year
    _record['publication_date'] = fake.date_this_year()
    data_store['posts'].append(_record)

# Generate rows for: comments
for _row_idx_comments in range(100):
    _record = {}
    # Primary key (sequential integer)
    _record['id'] = _row_idx_comments + 1
    # Foreign key -> posts.id
    _parent_ids = [r['id'] for r in data_store['posts']]
    _record['post_id'] = random.choice(_parent_ids)
    # Foreign key -> users.id
    _parent_ids = [r['id'] for r in data_store['users']]
    _record['user_id'] = random.choice(_parent_ids)
    # Faker: paragraph
    _record['text'] = fake.paragraph()
    # Faker: date_this_year
    _record['date_posted'] = fake.date_this_year()
    data_store['comments'].append(_record)

# Summary
for _tbl_name, _tbl_rows in data_store.items():
    print(f"Table '{{_tbl_name}}': {{len(_tbl_rows)}} rows")
