"""
Faker Generator (Code Generation Compiler)
===========================================

This module converts a validated Generation Plan JSON into executable
Python source code. It is a mechanical compiler with NO AI, NO heuristics,
and DETERMINISTIC output.

Stage B is a correctness-first generator:
- No pandas/numpy (use dict/list only)
- No vectorization (row-by-row explicit loops)
- No performance optimizations
- Explicit unconditional imports only

Input: Generation Plan JSON (from Stage A)
Output: Python source code string
"""

from typing import Any


# =============================================================================
# EXCEPTIONS
# =============================================================================

class CodeGenerationError(Exception):
    """Raised when code generation fails."""
    pass


# =============================================================================
# CODE TEMPLATES
# =============================================================================

HEADER_TEMPLATE = '''"""
Auto-generated synthetic data script.
Generated by: AI-Driven Synthetic Data Generator (Stage B)
"""

from faker import Faker
import random

# Initialize Faker with deterministic seed
fake = Faker()
Faker.seed({seed})
random.seed({seed})

# Data store: table_name -> list of records
data_store = {{}}
'''

TABLE_INIT_TEMPLATE = '''
# Initialize table: {table_name}
data_store['{table_name}'] = []
'''

TABLE_LOOP_START = '''
# Generate rows for: {table_name}
for _row_idx_{table_name} in range({row_count}):
    _record = {{}}
'''

PK_COLUMN_TEMPLATE = '''    # Primary key (sequential integer)
    _record['{col_name}'] = _row_idx_{table_name} + 1
'''

FK_COLUMN_TEMPLATE = '''    # Foreign key -> {ref_table}.{ref_column}
    _parent_ids = [r['{ref_column}'] for r in data_store['{ref_table}']]
    _record['{col_name}'] = random.choice(_parent_ids)
'''

FK_NULLABLE_TEMPLATE = '''    # Foreign key -> {ref_table}.{ref_column} (nullable)
    if random.random() < {null_prob}:
        _record['{col_name}'] = None
    else:
        _parent_ids = [r['{ref_column}'] for r in data_store['{ref_table}']]
        _record['{col_name}'] = random.choice(_parent_ids)
'''

FAKER_COLUMN_TEMPLATE = '''    # Faker: {provider}
    _record['{col_name}'] = fake.{provider}()
'''

FAKER_NULLABLE_TEMPLATE = '''    # Faker: {provider} (nullable)
    if random.random() < {null_prob}:
        _record['{col_name}'] = None
    else:
        _record['{col_name}'] = fake.{provider}()
'''

TABLE_LOOP_END = '''    data_store['{table_name}'].append(_record)
'''

FOOTER_TEMPLATE = '''
# Summary
for _tbl_name, _tbl_rows in data_store.items():
    print(f"Table '{{_tbl_name}}': {{len(_tbl_rows)}} rows")
'''


# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

def _generate_header(plan: dict) -> str:
    """Generate imports and setup code."""
    meta = plan.get("meta", {})
    seed = meta.get("faker_seed", 0)
    return HEADER_TEMPLATE.format(seed=seed)


def _generate_table_init(table_name: str) -> str:
    """Generate table initialization."""
    return TABLE_INIT_TEMPLATE.format(table_name=table_name)


def _generate_column_code(
    col: dict,
    table_name: str
) -> str:
    """Generate code for a single column."""
    col_name = col["name"]
    gen_type = col["generator_type"]
    
    if gen_type == "primary_key":
        return PK_COLUMN_TEMPLATE.format(
            col_name=col_name,
            table_name=table_name
        )
    
    elif gen_type == "foreign_key":
        refs = col.get("references", {})
        ref_table = refs.get("table", "")
        ref_column = refs.get("column", "id")
        is_nullable = col.get("is_nullable", False)
        null_prob = col.get("null_probability", 0.2)
        
        if is_nullable:
            return FK_NULLABLE_TEMPLATE.format(
                col_name=col_name,
                ref_table=ref_table,
                ref_column=ref_column,
                null_prob=null_prob
            )
        else:
            return FK_COLUMN_TEMPLATE.format(
                col_name=col_name,
                ref_table=ref_table,
                ref_column=ref_column
            )
    
    elif gen_type == "faker":
        provider = col.get("faker_provider", "lexify")
        is_nullable = col.get("is_nullable", False)
        null_prob = col.get("null_probability", 0.2)
        
        if is_nullable:
            return FAKER_NULLABLE_TEMPLATE.format(
                col_name=col_name,
                provider=provider,
                null_prob=null_prob
            )
        else:
            return FAKER_COLUMN_TEMPLATE.format(
                col_name=col_name,
                provider=provider
            )
    
    else:
        raise CodeGenerationError(
            f"Unknown generator_type '{gen_type}' for column '{col_name}'"
        )


def _generate_table_code(table: dict) -> str:
    """Generate code for a single table."""
    table_name = table["name"]
    row_count = table.get("row_count", 50)
    columns = table.get("columns", [])
    
    parts = []
    
    # Loop start
    parts.append(TABLE_LOOP_START.format(
        table_name=table_name,
        row_count=row_count
    ))
    
    # Column generation
    for col in columns:
        parts.append(_generate_column_code(col, table_name))
    
    # Loop end (append record)
    parts.append(TABLE_LOOP_END.format(table_name=table_name))
    
    return "".join(parts)


# =============================================================================
# PUBLIC INTERFACE
# =============================================================================

def generate_python_code(plan: dict) -> str:
    """
    Generate executable Python code from a Generation Plan.
    
    This is the main entry point for Stage B code generation.
    The input plan is assumed to be valid (pre-validated by Stage A).
    
    Args:
        plan: Validated Generation Plan JSON.
        
    Returns:
        Python source code as a string.
        
    Raises:
        CodeGenerationError: If code generation fails.
    """
    if not plan:
        raise CodeGenerationError("Empty plan provided.")
    
    execution_order = plan.get("execution_order", [])
    if not execution_order:
        raise CodeGenerationError("Plan has no execution_order.")
    
    # Build table lookup
    tables = plan.get("tables", [])
    table_lookup = {t["name"]: t for t in tables}
    
    # Generate code parts
    code_parts = []
    
    # Header
    code_parts.append(_generate_header(plan))
    
    # Initialize all tables
    for table_name in execution_order:
        code_parts.append(_generate_table_init(table_name))
    
    # Generate each table in order
    for table_name in execution_order:
        table = table_lookup.get(table_name)
        if not table:
            raise CodeGenerationError(
                f"Table '{table_name}' in execution_order not found in tables."
            )
        code_parts.append(_generate_table_code(table))
    
    # Footer
    code_parts.append(FOOTER_TEMPLATE)
    
    return "".join(code_parts)
